services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eventapi_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # ports:
    #   - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=eventapi_db
      - DB_USER=user
      - DB_PASSWORD=password

volumes:
  db-data: